import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const typegen = `// This file is auto-generated by scripts/typegen.ts
// Do not edit this file manually

export interface RuleOptions {
  // Auto-generated rule options
}

export type ConfigNames = 'eslint' | 'stylelint' | 'prettier' | 'commitlint' | 'lint-staged'
`

writeFileSync(resolve(__dirname, '../src/typegen.ts'), typegen)
console.log('Generated typegen.ts')
