import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { readFileSync } from 'node:fs'

const packageJson = JSON.parse(
  readFileSync(resolve(__dirname, '../package.json'), 'utf-8')
)

const versiongen = `// This file is auto-generated by scripts/versiongen.ts
// Do not edit this file manually

export const VERSION = '${packageJson.version}'
`

writeFileSync(resolve(__dirname, '../src/version.ts'), versiongen)
console.log('Generated version.ts')

